apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "solr-cloud.name" . }}"-zookeeper" 
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: {{ template "solr-cloud.name" . }}"-zookeeper"
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: {{ .Values.zookeeper.pvc_name }}
          # claimName: task-zookeeper-pv-claim
      containers: 
      - name: zookeeper
        image: "{{ .Values.zookeeper.image.repository }}:{{ .Values.zookeeper.image.tag }}"
        imagePullPolicy: {{ .Values.zookeeper.image.pullPolicy }}
        # image: zookeeper:latest
        volumeMounts:
        - name: vol
          mountPath: /store
        ports:
        - name: zookeeper-port
          containerPort: 2181
        env:
          - name: ZOO_MY_ID
            valueFrom: 
              configMapKeyRef:
                # name: zookeeper-config
                name: {{ template "solr-cloud.name" . }}"-zookeeper"
                key: zooMyId
          - name: ZOO_LOG_DIR
            valueFrom: 
              configMapKeyRef:
                name: {{ template "solr-cloud.name" . }}"-zookeeper"
                key: zooLogDir
          - name: ZOO_DATA_DIR
            valueFrom: 
              configMapKeyRef:
                name: {{ template "solr-cloud.name" . }}"-zookeeper"
                key: zooDataDir
          - name: ZOO_DATA_LOG_DIR
            valueFrom: 
              configMapKeyRef:
                name: {{ template "solr-cloud.name" . }}"-zookeeper"
                key: zooDataLogDir
          - name: ZOO_PORT
            valueFrom: 
              configMapKeyRef:
                name: {{ template "solr-cloud.name" . }}"-zookeeper"
                key: zooPort
