apiVersion: v1
kind: Service
metadata:
  name: {{ template "solr-cloud.name" . }}"-zookeeper"
spec:
  ports:
  - port: 32181
    targetPort: 32181
    nodePort: 32181
    protocol: TCP
  selector:
    app: {{ template "solr-cloud.name" . }}"-zookeeper"
  type: NodePort
